"""empty message

Revision ID: 00d891ec6e83
Revises: 09874a0f6067
Create Date: 2020-05-20 17:01:56.507590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00d891ec6e83'
down_revision = '09874a0f6067'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('question', sa.Column('name', sa.String(length=64), nullable=True))
    op.add_column('question', sa.Column('solution', sa.Text(), nullable=True))
    op.add_column('question', sa.Column('solution_space', sa.Text(), nullable=True))
    op.create_index(op.f('ix_question_name'), 'question', ['name'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_name'), table_name='question')
    op.drop_column('question', 'solution_space')
    op.drop_column('question', 'solution')
    op.drop_column('question', 'name')
    # ### end Alembic commands ###
