"""empty message

Revision ID: 09874a0f6067
Revises: 
Create Date: 2020-05-19 13:48:45.814526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09874a0f6067'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exam',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('questions', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_exam_course'), 'exam', ['course'], unique=False)
    op.create_index(op.f('ix_exam_subject'), 'exam', ['subject'], unique=False)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(length=64), nullable=True),
    sa.Column('subject', sa.String(length=64), nullable=True),
    sa.Column('question', sa.Text(), nullable=True),
    sa.Column('question_type', sa.String(length=64), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_question_course'), 'question', ['course'], unique=False)
    op.create_index(op.f('ix_question_question_type'), 'question', ['question_type'], unique=False)
    op.create_index(op.f('ix_question_subject'), 'question', ['subject'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_question_subject'), table_name='question')
    op.drop_index(op.f('ix_question_question_type'), table_name='question')
    op.drop_index(op.f('ix_question_course'), table_name='question')
    op.drop_table('question')
    op.drop_index(op.f('ix_exam_subject'), table_name='exam')
    op.drop_index(op.f('ix_exam_course'), table_name='exam')
    op.drop_table('exam')
    # ### end Alembic commands ###
